#!/bin/bash
# calibre-update:version:0.6
#author: @nanopc

function update() {
  wget --no-check-certificate -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('/home/$USER')"
}

function notify(){

s=$1
#Change the logo paht to match your distribution logo.
notify-send -u normal Calibre "$1" -i /usr/share/pixmaps/debian-logo.png
}

function yesno() {
	OPTION=
	while [ "$OPTION" != "yes" -a "$OPTION" != "no" ]; do

		 echo -e "\e[1;33m  Close Calibre and update? [yes/no] \e[0m"
		
		read OPTION
	done
	if [ "$OPTION" != "yes" ]; then
		exit 1
	fi
}

echo -e "\e[1;36m This script will install Calibre from Calibre's repository \e[0m"
echo -e "\e[1;36m on your machine on /home/$USER \e[0m"
echo


#ROOT user?
if [[ $EUID -ne 0 ]]; then
  echo -e "\e[1;41m You must be a root user \e[0m"
  sudo -v
fi
echo "Cheking versions..."
# GET THE DIR WE'RE IN
dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#Get the number of the lastest version . I'm sure there's a better way to do this :)
wget -O  $dir/latest "http://code.calibre-ebook.com/latest" >/dev/null 2>&1

#dirty fix to match version --calibre output
a="calibre (calibre "
b=")"
# Keep the latest version

str=$(cat "$dir/latest")
i=$((${#str}-1))

if [ "${str:$i:1}" -eq "0" ] # BUG version .0
then

version_web=$a${str::-2}$b

else

version_web=$a$(cat "$dir/latest")$b

fi

version_local=$(calibre --version)


#Compare both versions and update if necessary
if [ "$version_web" == "$version_local" ]
then
  echo -e "\e[1;36m No need for update \e[0m"
  notify "No need for update"
else
  echo -e "\e[1;32m  Versions are: LATEST:  $version_web , LOCAL: $version_local \e[0m"

    yesno

    calibre -s
    sleep 3

    notify "Updating"
    update
    notify "Updated"

fi

#Cleaning up the mess
if [ -a ~/linux-installer.py ]
then

rm ~/linux-installer.py

fi

rm $dir/latest


exit 1
