#!/bin/bash
# calibre-update:version:0.7
#author: @nanopc

install_directory="/home/$USER/09.Software"

readonly RED="\033[01;31m"
readonly GREEN="\033[01;32m"
readonly BLUE="\033[01;36m"
readonly YELLOW="\033[00;33m"
readonly BOLD="\033[01m"
readonly END="\033[0m"

function update() {
  wget --no-check-certificate -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python3 -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('$install_directory')"
}

function notify(){
#Change the logo path to match your distribution logo.
notify-send -u normal Calibre "$1" -i /usr/share/pixmaps/debian-logo.png
}

function yesno() {
	OPTION=
	while [ "$OPTION" != "yes" -a "$OPTION" != "no" ]; do

		 echo -e $RED"Close Calibre and update? [yes/no]"$END
		
		read OPTION
	done
	if [ "$OPTION" != "yes" ]; then
		exit 1
	fi
}




#ROOT user?
if [[ $EUID -ne 0 ]]; then
  #echo -e "\e[1;41m You must be a root user \e[0m"
  sudo -v
fi
echo "Checking versions..."
# GET THE DIR WE'RE IN
dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#Get the number of the lastest version . I'm sure there's a better way to do this :)
wget -O  $dir/latest "http://code.calibre-ebook.com/latest" >/dev/null 2>&1

#dirty fix to match version --calibre output
a="calibre (calibre "
b=")"
# Keep the latest version

str=$(cat "$dir/latest")
i=$((${#str}-1))

if [ "${str:$i:1}" -eq "0" ] # BUG version .0
then

version_web=$a${str::-2}$b

else

version_web=$a$(cat "$dir/latest")$b

fi
# In case Calibre is not installed
if ! type "calibre" > /dev/null; 
then
  echo "Calibre is not installed"
  update
fi

version_local=$($install_directory/calibre/calibre --version)


#Compare both versions and update if necessary
if [ "$version_web" == "$version_local" ]
then
  echo -e $BLUE"No need for update \e[0m"$END
  notify "No need for update"
else
  echo -e $BLUE"This script will install Calibre from Calibre's repository"$END
  echo -e $BLUE"on your machine on $install_directory/calibre"$END
  echo ""
  echo -e $GREEN"Versions are: LATEST:  $version_web , LOCAL: $version_local"$END

    yesno
    #closing calibre
    calibre -s
    sleep 3

    notify "Updating"
    update
    notify "Updated"

fi

#Cleaning up the mess
if [ -a ~/linux-installer.py ]
then
rm ~/linux-installer.py
fi
rm $dir/latest

exit 1
